### ISSUE TITLE
waque init Error: Request failed with status code 401

### ISSUE THREAD

**Issue by andyxm** [yesmeck/waque#10]
Error: Request failed with status code 401
    at createError (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/core/createError.js:16:15)
    at settle (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/adapters/http.js
:202:11)

**Comment by yesmeck** [comment]
先登录。

```bash
$ waque login
```

**Comment by andyxm** [comment]
@yesmeck 已经登录了,并且弹出来去网页授权了

**Comment by yesmeck** [comment]
那确认下是否有知识库权限吧，另外可以用下面的命令来看更多日志：

```
$ DEBUG=axios waque upload
```

**Comment by andyxm** [comment]
@yesmeck 产权权限在哪里看的

**Comment by yesmeck** [comment]
语雀上

**Comment by andyxm** [comment]
相同的账户，我在家里就无法waque init 报这个错误，我在公司电脑就没问题

**Comment by yesmeck** [comment]
试试这个吧

```
$ DEBUG=axios waque upload
```

**Comment by andyxm** [comment]
怎么执行这个呢，不是内部文件
'DEBUG' 不是内部或外部命令，也不是可运行的程序
或批处理文件。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei Zhu"<notifications@github.com&gt;; 
发送时间: 2020年4月29日(星期三) 晚上11:30
收件人: "yesmeck/waque"<waque@noreply.github.com&gt;; 
抄送: "『燭火夜光』"<407311996@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yesmeck/waque] waque init Error: Request failed with status code 401 (#10)





 
试试这个吧
 $ DEBUG=axios waque upload

**Comment by yesmeck** [comment]
奥，你是  Windows 吧？你先装个  `cross-env`。

```
npm install cross-env -g
```

然后：

```
cross-env DEBUG=axios waque upload
```

**Comment by andyxm** [comment]
看下文档像是没授权的样子，但我确实登录时候授权了啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wei Zhu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 凌晨0:06
收件人:&nbsp;"yesmeck/waque"<waque@noreply.github.com&gt;;
抄送:&nbsp;"『燭火夜光』"<407311996@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yesmeck/waque] waque init Error: Request failed with status code 401 (#10)





 
奥，你是  Windows 吧？你先装个  cross-env。
 npm install cross-env -g  
然后：
 cross-env DEBUG=axios waque upload  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的在线文档

                        新建文档.docx (9.94K)进入查看页面https://mail.qq.com/cgi-bin/docedit_read?func=3rdread&key=v2_252c364ed8c89f9bc68890f7ee804

**Comment by yesmeck** [comment]
把日志贴出来我看看吧(注意把 token 隐藏掉)

**Comment by andyxm** [comment]
你说的日志在哪里查看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei Zhu"<notifications@github.com&gt;; 
发送时间: 2020年4月30日(星期四) 凌晨0:52
收件人: "yesmeck/waque"<waque@noreply.github.com&gt;; 
抄送: "『燭火夜光』"<407311996@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yesmeck/waque] waque init Error: Request failed with status code 401 (#10)





 
把日子贴出来我看看吧(注意把 token 隐藏掉)

**Comment by yesmeck** [comment]
看我上面说的，运行 

```
cross-env DEBUG=axios waque upload
```

**Comment by andyxm** [comment]
E:\waque&gt;cross-env DEBUG=axios waque upload
&nbsp; axios Request /user +0ms
&nbsp; axios Boom Error: Request failed with status code 401
&nbsp; &nbsp; at createError (E:\Nodejs\node_global\node_modules\waque\node_modules\axios\lib\core\createError.js:16:15)
&nbsp; &nbsp; at settle (E:\Nodejs\node_global\node_modules\waque\node_modules\axios\lib\core\settle.js:18:12)
&nbsp; &nbsp; at IncomingMessage.handleStreamEnd (E:\Nodejs\node_global\node_modules\waque\node_modules\axios\lib\adapters\http.js
:202:11)
&nbsp; &nbsp; at IncomingMessage.emit (events.js:323:22)
&nbsp; &nbsp; at endReadableNT (_stream_readable.js:1204:12)
&nbsp; &nbsp; at processTicksAndRejections (internal/process/task_queues.js:84:21) {
&nbsp; config: {
&nbsp; &nbsp; adapter: [Function: httpAdapter],
&nbsp; &nbsp; transformRequest: { '0': [Function: transformRequest] },
&nbsp; &nbsp; transformResponse: { '0': [Function: transformResponse] },
&nbsp; &nbsp; timeout: 0,
&nbsp; &nbsp; xsrfCookieName: 'XSRF-TOKEN',
&nbsp; &nbsp; xsrfHeaderName: 'X-XSRF-TOKEN',
&nbsp; &nbsp; maxContentLength: -1,
&nbsp; &nbsp; validateStatus: [Function: validateStatus],
&nbsp; &nbsp; headers: {
&nbsp; &nbsp; &nbsp; Accept: 'application/json, text/plain, */*',
&nbsp; &nbsp; &nbsp; 'X-Auth-Token': 'GeQmKDnUjnVBFgWEnI1BS8Kskan3Uc9kuZwsmPyE',
&nbsp; &nbsp; &nbsp; 'User-Agent': 'axios/0.18.1'
&nbsp; &nbsp; },
&nbsp; &nbsp; method: 'get',
&nbsp; &nbsp; baseURL: 'https://www.yuque.com/api/v2',
&nbsp; &nbsp; url: 'https://www.yuque.com/api/v2/user',
&nbsp; &nbsp; data: undefined
&nbsp; },
&nbsp; request: ClientRequest {
&nbsp; &nbsp; _events: [Object: null prototype] {
&nbsp; &nbsp; &nbsp; socket: [Function],
&nbsp; &nbsp; &nbsp; abort: [Function],
&nbsp; &nbsp; &nbsp; aborted: [Function],
&nbsp; &nbsp; &nbsp; error: [Function],
&nbsp; &nbsp; &nbsp; timeout: [Function],
&nbsp; &nbsp; &nbsp; prefinish: [Function: requestOnPrefinish]
&nbsp; &nbsp; },
&nbsp; &nbsp; _eventsCount: 6,
&nbsp; &nbsp; _maxListeners: undefined,
&nbsp; &nbsp; outputData: [],
&nbsp; &nbsp; outputSize: 0,
&nbsp; &nbsp; writable: true,
&nbsp; &nbsp; _last: true,
&nbsp; &nbsp; chunkedEncoding: false,
&nbsp; &nbsp; shouldKeepAlive: false,
&nbsp; &nbsp; useChunkedEncodingByDefault: false,
&nbsp; &nbsp; sendDate: false,
&nbsp; &nbsp; _removedConnection: false,
&nbsp; &nbsp; _removedContLen: false,
&nbsp; &nbsp; _removedTE: false,
&nbsp; &nbsp; _contentLength: 0,
&nbsp; &nbsp; _hasBody: true,
&nbsp; &nbsp; _trailer: '',
&nbsp; &nbsp; finished: true,
&nbsp; &nbsp; _headerSent: true,
&nbsp; &nbsp; socket: TLSSocket {
&nbsp; &nbsp; &nbsp; _tlsOptions: [Object],
&nbsp; &nbsp; &nbsp; _secureEstablished: true,
&nbsp; &nbsp; &nbsp; _securePending: false,
&nbsp; &nbsp; &nbsp; _newSessionPending: false,
&nbsp; &nbsp; &nbsp; _controlReleased: true,
&nbsp; &nbsp; &nbsp; _SNICallback: null,
&nbsp; &nbsp; &nbsp; servername: 'www.yuque.com',
&nbsp; &nbsp; &nbsp; alpnProtocol: false,
&nbsp; &nbsp; &nbsp; authorized: true,
&nbsp; &nbsp; &nbsp; authorizationError: null,
&nbsp; &nbsp; &nbsp; encrypted: true,
&nbsp; &nbsp; &nbsp; _events: [Object: null prototype],
&nbsp; &nbsp; &nbsp; _eventsCount: 9,
&nbsp; &nbsp; &nbsp; connecting: false,
&nbsp; &nbsp; &nbsp; _hadError: false,
&nbsp; &nbsp; &nbsp; _parent: null,
&nbsp; &nbsp; &nbsp; _host: 'www.yuque.com',
&nbsp; &nbsp; &nbsp; _readableState: [ReadableState],
&nbsp; &nbsp; &nbsp; readable: true,
&nbsp; &nbsp; &nbsp; _maxListeners: undefined,
&nbsp; &nbsp; &nbsp; _writableState: [WritableState],
&nbsp; &nbsp; &nbsp; writable: false,
&nbsp; &nbsp; &nbsp; allowHalfOpen: false,
&nbsp; &nbsp; &nbsp; _sockname: null,
&nbsp; &nbsp; &nbsp; _pendingData: null,
&nbsp; &nbsp; &nbsp; _pendingEncoding: '',
&nbsp; &nbsp; &nbsp; server: undefined,
&nbsp; &nbsp; &nbsp; _server: null,
&nbsp; &nbsp; &nbsp; ssl: [TLSWrap],
&nbsp; &nbsp; &nbsp; _requestCert: true,
&nbsp; &nbsp; &nbsp; _rejectUnauthorized: true,
&nbsp; &nbsp; &nbsp; parser: null,
&nbsp; &nbsp; &nbsp; _httpMessage: [Circular],
&nbsp; &nbsp; &nbsp; [Symbol(res)]: [TLSWrap],
&nbsp; &nbsp; &nbsp; [Symbol(asyncId)]: 29,
&nbsp; &nbsp; &nbsp; [Symbol(kHandle)]: [TLSWrap],
&nbsp; &nbsp; &nbsp; [Symbol(lastWriteQueueSize)]: 0,
&nbsp; &nbsp; &nbsp; [Symbol(timeout)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kBuffer)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kBufferCb)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kBufferGen)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kCapture)]: false,
&nbsp; &nbsp; &nbsp; [Symbol(kBytesRead)]: 0,
&nbsp; &nbsp; &nbsp; [Symbol(kBytesWritten)]: 0,
&nbsp; &nbsp; &nbsp; [Symbol(connect-options)]: [Object]
&nbsp; &nbsp; },
&nbsp; &nbsp; connection: TLSSocket {
&nbsp; &nbsp; &nbsp; _tlsOptions: [Object],
&nbsp; &nbsp; &nbsp; _secureEstablished: true,
&nbsp; &nbsp; &nbsp; _securePending: false,
&nbsp; &nbsp; &nbsp; _newSessionPending: false,
&nbsp; &nbsp; &nbsp; _controlReleased: true,
&nbsp; &nbsp; &nbsp; _SNICallback: null,
&nbsp; &nbsp; &nbsp; servername: 'www.yuque.com',
&nbsp; &nbsp; &nbsp; alpnProtocol: false,
&nbsp; &nbsp; &nbsp; authorized: true,
&nbsp; &nbsp; &nbsp; authorizationError: null,
&nbsp; &nbsp; &nbsp; encrypted: true,
&nbsp; &nbsp; &nbsp; _events: [Object: null prototype],
&nbsp; &nbsp; &nbsp; _eventsCount: 9,
&nbsp; &nbsp; &nbsp; connecting: false,
&nbsp; &nbsp; &nbsp; _hadError: false,
&nbsp; &nbsp; &nbsp; _parent: null,
&nbsp; &nbsp; &nbsp; _host: 'www.yuque.com',
&nbsp; &nbsp; &nbsp; _readableState: [ReadableState],
&nbsp; &nbsp; &nbsp; readable: true,
&nbsp; &nbsp; &nbsp; _maxListeners: undefined,
&nbsp; &nbsp; &nbsp; _writableState: [WritableState],
&nbsp; &nbsp; &nbsp; writable: false,
&nbsp; &nbsp; &nbsp; allowHalfOpen: false,
&nbsp; &nbsp; &nbsp; _sockname: null,
&nbsp; &nbsp; &nbsp; _pendingData: null,
&nbsp; &nbsp; &nbsp; _pendingEncoding: '',
&nbsp; &nbsp; &nbsp; server: undefined,
&nbsp; &nbsp; &nbsp; _server: null,
&nbsp; &nbsp; &nbsp; ssl: [TLSWrap],
&nbsp; &nbsp; &nbsp; _requestCert: true,
&nbsp; &nbsp; &nbsp; _rejectUnauthorized: true,
&nbsp; &nbsp; &nbsp; parser: null,
&nbsp; &nbsp; &nbsp; _httpMessage: [Circular],
&nbsp; &nbsp; &nbsp; [Symbol(res)]: [TLSWrap],
&nbsp; &nbsp; &nbsp; [Symbol(asyncId)]: 29,
&nbsp; &nbsp; &nbsp; [Symbol(kHandle)]: [TLSWrap],
&nbsp; &nbsp; &nbsp; [Symbol(lastWriteQueueSize)]: 0,
&nbsp; &nbsp; &nbsp; [Symbol(timeout)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kBuffer)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kBufferCb)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kBufferGen)]: null,
&nbsp; &nbsp; &nbsp; [Symbol(kCapture)]: false,
&nbsp; &nbsp; &nbsp; [Symbol(kBytesRead)]: 0,
&nbsp; &nbsp; &nbsp; [Symbol(kBytesWritten)]: 0,
&nbsp; &nbsp; &nbsp; [Symbol(connect-options)]: [Object]
&nbsp; &nbsp; },
&nbsp; &nbsp; _header: 'GET /api/v2/user HTTP/1.1\r\n' +
&nbsp; &nbsp; &nbsp; 'Accept: application/json, text/plain, */*\r\n' +
&nbsp; &nbsp; &nbsp; 'X-Auth-Token: xxx\r\n' +
&nbsp; &nbsp; &nbsp; 'User-Agent: axios/0.18.1\r\n' +
&nbsp; &nbsp; &nbsp; 'Host: www.yuque.com\r\n' +
&nbsp; &nbsp; &nbsp; 'Connection: close\r\n' +
&nbsp; &nbsp; &nbsp; '\r\n',
&nbsp; &nbsp; _onPendingData: [Function: noopPendingOutput],
&nbsp; &nbsp; agent: Agent {
&nbsp; &nbsp; &nbsp; _events: [Object: null prototype],
&nbsp; &nbsp; &nbsp; _eventsCount: 2,
&nbsp; &nbsp; &nbsp; _maxListeners: undefined,
&nbsp; &nbsp; &nbsp; defaultPort: 443,
&nbsp; &nbsp; &nbsp; protocol: 'https:',
&nbsp; &nbsp; &nbsp; options: [Object],
&nbsp; &nbsp; &nbsp; requests: {},
&nbsp; &nbsp; &nbsp; sockets: [Object],
&nbsp; &nbsp; &nbsp; freeSockets: {},
&nbsp; &nbsp; &nbsp; keepAliveMsecs: 1000,
&nbsp; &nbsp; &nbsp; keepAlive: false,
&nbsp; &nbsp; &nbsp; maxSockets: Infinity,
&nbsp; &nbsp; &nbsp; maxFreeSockets: 256,
&nbsp; &nbsp; &nbsp; maxCachedSessions: 100,
&nbsp; &nbsp; &nbsp; _sessionCache: [Object],
&nbsp; &nbsp; &nbsp; [Symbol(kCapture)]: false
&nbsp; &nbsp; },
&nbsp; &nbsp; socketPath: undefined,
&nbsp; &nbsp; method: 'GET',
&nbsp; &nbsp; insecureHTTPParser: undefined,
&nbsp; &nbsp; path: '/api/v2/user',
&nbsp; &nbsp; _ended: true,
&nbsp; &nbsp; res: IncomingMessage {
&nbsp; &nbsp; &nbsp; _readableState: [ReadableState],
&nbsp; &nbsp; &nbsp; readable: false,
&nbsp; &nbsp; &nbsp; _events: [Object: null prototype],
&nbsp; &nbsp; &nbsp; _eventsCount: 3,
&nbsp; &nbsp; &nbsp; _maxListeners: undefined,
&nbsp; &nbsp; &nbsp; socket: [TLSSocket],
&nbsp; &nbsp; &nbsp; connection: [TLSSocket],
&nbsp; &nbsp; &nbsp; httpVersionMajor: 1,
&nbsp; &nbsp; &nbsp; httpVersionMinor: 1,
&nbsp; &nbsp; &nbsp; httpVersion: '1.1',
&nbsp; &nbsp; &nbsp; complete: true,
&nbsp; &nbsp; &nbsp; headers: [Object],
&nbsp; &nbsp; &nbsp; rawHeaders: [Array],
&nbsp; &nbsp; &nbsp; trailers: {},
&nbsp; &nbsp; &nbsp; rawTrailers: [],
&nbsp; &nbsp; &nbsp; aborted: false,
&nbsp; &nbsp; &nbsp; upgrade: false,
&nbsp; &nbsp; &nbsp; url: '',
&nbsp; &nbsp; &nbsp; method: null,
&nbsp; &nbsp; &nbsp; statusCode: 401,
&nbsp; &nbsp; &nbsp; statusMessage: 'Unauthorized',
&nbsp; &nbsp; &nbsp; client: [TLSSocket],
&nbsp; &nbsp; &nbsp; _consuming: false,
&nbsp; &nbsp; &nbsp; _dumped: false,
&nbsp; &nbsp; &nbsp; req: [Circular],
&nbsp; &nbsp; &nbsp; responseUrl: 'https://www.yuque.com/api/v2/user',
&nbsp; &nbsp; &nbsp; redirects: [],
&nbsp; &nbsp; &nbsp; [Symbol(kCapture)]: false
&nbsp; &nbsp; },
&nbsp; &nbsp; aborted: false,
&nbsp; &nbsp; timeoutCb: null,
&nbsp; &nbsp; upgradeOrConnect: false,
&nbsp; &nbsp; parser: null,
&nbsp; &nbsp; maxHeadersCount: null,
&nbsp; &nbsp; reusedSocket: false,
&nbsp; &nbsp; _redirectable: Writable {
&nbsp; &nbsp; &nbsp; _writableState: [WritableState],
&nbsp; &nbsp; &nbsp; writable: true,
&nbsp; &nbsp; &nbsp; _events: [Object: null prototype],
&nbsp; &nbsp; &nbsp; _eventsCount: 2,
&nbsp; &nbsp; &nbsp; _maxListeners: undefined,
&nbsp; &nbsp; &nbsp; _options: [Object],
&nbsp; &nbsp; &nbsp; _redirectCount: 0,
&nbsp; &nbsp; &nbsp; _redirects: [],
&nbsp; &nbsp; &nbsp; _requestBodyLength: 0,
&nbsp; &nbsp; &nbsp; _requestBodyBuffers: [],
&nbsp; &nbsp; &nbsp; _onNativeResponse: [Function],
&nbsp; &nbsp; &nbsp; _currentRequest: [Circular],
&nbsp; &nbsp; &nbsp; _currentUrl: 'https://www.yuque.com/api/v2/user',
&nbsp; &nbsp; &nbsp; [Symbol(kCapture)]: false
&nbsp; &nbsp; },
&nbsp; &nbsp; [Symbol(kCapture)]: false,
&nbsp; &nbsp; [Symbol(kNeedDrain)]: false,
&nbsp; &nbsp; [Symbol(corked)]: 0,
&nbsp; &nbsp; [Symbol(kOutHeaders)]: [Object: null prototype] {
&nbsp; &nbsp; &nbsp; accept: [Array],
&nbsp; &nbsp; &nbsp; 'x-auth-token': [Array],
&nbsp; &nbsp; &nbsp; 'user-agent': [Array],
&nbsp; &nbsp; &nbsp; host: [Array]
&nbsp; &nbsp; }
&nbsp; },
&nbsp; response: {
&nbsp; &nbsp; status: 401,
&nbsp; &nbsp; statusText: 'Unauthorized',
&nbsp; &nbsp; headers: {
&nbsp; &nbsp; &nbsp; date: 'Sat, 02 May 2020 15:40:36 GMT',
&nbsp; &nbsp; &nbsp; 'content-type': 'application/json; charset=utf-8',
&nbsp; &nbsp; &nbsp; 'content-length': '52',
&nbsp; &nbsp; &nbsp; connection: 'close',
&nbsp; &nbsp; &nbsp; vary: 'Origin',
&nbsp; &nbsp; &nbsp; 'x-server-id': 'prod-6',
&nbsp; &nbsp; &nbsp; 'request-id': '0a1c954c158843403649665794950',
&nbsp; &nbsp; &nbsp; 'x-cchm': 'h:0,m:0',
&nbsp; &nbsp; &nbsp; 'x-xss-protection': '1; mode=block',
&nbsp; &nbsp; &nbsp; 'x-content-type-options': 'nosniff',
&nbsp; &nbsp; &nbsp; 'x-download-options': 'noopen',
&nbsp; &nbsp; &nbsp; 'strict-transport-security': 'max-age=31536000',
&nbsp; &nbsp; &nbsp; 'x-readtime': '9'
&nbsp; &nbsp; },
&nbsp; &nbsp; config: {
&nbsp; &nbsp; &nbsp; adapter: [Function: httpAdapter],
&nbsp; &nbsp; &nbsp; transformRequest: [Object],
&nbsp; &nbsp; &nbsp; transformResponse: [Object],
&nbsp; &nbsp; &nbsp; timeout: 0,
&nbsp; &nbsp; &nbsp; xsrfCookieName: 'XSRF-TOKEN',
&nbsp; &nbsp; &nbsp; xsrfHeaderName: 'X-XSRF-TOKEN',
&nbsp; &nbsp; &nbsp; maxContentLength: -1,
&nbsp; &nbsp; &nbsp; validateStatus: [Function: validateStatus],
&nbsp; &nbsp; &nbsp; headers: [Object],
&nbsp; &nbsp; &nbsp; method: 'get',
&nbsp; &nbsp; &nbsp; baseURL: 'https://www.yuque.com/api/v2',
&nbsp; &nbsp; &nbsp; url: 'https://www.yuque.com/api/v2/user',
&nbsp; &nbsp; &nbsp; data: undefined
&nbsp; &nbsp; },
&nbsp; &nbsp; request: ClientRequest {
&nbsp; &nbsp; &nbsp; _events: [Object: null prototype],
&nbsp; &nbsp; &nbsp; _eventsCount: 6,
&nbsp; &nbsp; &nbsp; _maxListeners: undefined,
&nbsp; &nbsp; &nbsp; outputData: [],
&nbsp; &nbsp; &nbsp; outputSize: 0,
&nbsp; &nbsp; &nbsp; writable: true,
&nbsp; &nbsp; &nbsp; _last: true,
&nbsp; &nbsp; &nbsp; chunkedEncoding: false,
&nbsp; &nbsp; &nbsp; shouldKeepAlive: false,
&nbsp; &nbsp; &nbsp; useChunkedEncodingByDefault: false,
&nbsp; &nbsp; &nbsp; sendDate: false,
&nbsp; &nbsp; &nbsp; _removedConnection: false,
&nbsp; &nbsp; &nbsp; _removedContLen: false,
&nbsp; &nbsp; &nbsp; _removedTE: false,
&nbsp; &nbsp; &nbsp; _contentLength: 0,
&nbsp; &nbsp; &nbsp; _hasBody: true,
&nbsp; &nbsp; &nbsp; _trailer: '',
&nbsp; &nbsp; &nbsp; finished: true,
&nbsp; &nbsp; &nbsp; _headerSent: true,
&nbsp; &nbsp; &nbsp; socket: [TLSSocket],
&nbsp; &nbsp; &nbsp; connection: [TLSSocket],
&nbsp; &nbsp; &nbsp; _header: 'GET /api/v2/user HTTP/1.1\r\n' +
&nbsp; &nbsp; &nbsp; &nbsp; 'Accept: application/json, text/plain, */*\r\n' +
&nbsp; &nbsp; &nbsp; &nbsp; 'X-Auth-Token: xxx\r\n' +
&nbsp; &nbsp; &nbsp; &nbsp; 'User-Agent: axios/0.18.1\r\n' +
&nbsp; &nbsp; &nbsp; &nbsp; 'Host: www.yuque.com\r\n' +
&nbsp; &nbsp; &nbsp; &nbsp; 'Connection: close\r\n' +
&nbsp; &nbsp; &nbsp; &nbsp; '\r\n',
&nbsp; &nbsp; &nbsp; _onPendingData: [Function: noopPendingOutput],
&nbsp; &nbsp; &nbsp; agent: [Agent],
&nbsp; &nbsp; &nbsp; socketPath: undefined,
&nbsp; &nbsp; &nbsp; method: 'GET',
&nbsp; &nbsp; &nbsp; insecureHTTPParser: undefined,
&nbsp; &nbsp; &nbsp; path: '/api/v2/user',
&nbsp; &nbsp; &nbsp; _ended: true,
&nbsp; &nbsp; &nbsp; res: [IncomingMessage],
&nbsp; &nbsp; &nbsp; aborted: false,
&nbsp; &nbsp; &nbsp; timeoutCb: null,
&nbsp; &nbsp; &nbsp; upgradeOrConnect: false,
&nbsp; &nbsp; &nbsp; parser: null,
&nbsp; &nbsp; &nbsp; maxHeadersCount: null,
&nbsp; &nbsp; &nbsp; reusedSocket: false,
&nbsp; &nbsp; &nbsp; _redirectable: [Writable],
&nbsp; &nbsp; &nbsp; [Symbol(kCapture)]: false,
&nbsp; &nbsp; &nbsp; [Symbol(kNeedDrain)]: false,
&nbsp; &nbsp; &nbsp; [Symbol(corked)]: 0,
&nbsp; &nbsp; &nbsp; [Symbol(kOutHeaders)]: [Object: null prototype]
&nbsp; &nbsp; },
&nbsp; &nbsp; data: { status: 401, message: 'X-Auth-Token missing user' }
&nbsp; }
} +217ms
Error: Request failed with status code 401
&nbsp; &nbsp; at createError (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/core/createError.js:16:15)
&nbsp; &nbsp; at settle (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/core/settle.js:18:12)
&nbsp; &nbsp; at IncomingMessage.handleStreamEnd (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/adapters/http.js
:202:11)





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei Zhu"<notifications@github.com&gt;; 
发送时间: 2020年5月2日(星期六) 晚上11:40
收件人: "yesmeck/waque"<waque@noreply.github.com&gt;; 
抄送: "『燭火夜光』"<407311996@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yesmeck/waque] waque init Error: Request failed with status code 401 (#10)





 
看我上面说的，运行
 cross-env DEBUG=axios waque upload

**Comment by yesmeck** [comment]
@andyxm 收到，日志里暴露 token，我先删掉了

**Comment by andyxm** [comment]
好的，感谢 另外我公司同一个账户电脑用着没问题，家里的就这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei Zhu"<notifications@github.com&gt;; 
发送时间: 2020年5月2日(星期六) 晚上11:45
收件人: "yesmeck/waque"<waque@noreply.github.com&gt;; 
抄送: "『燭火夜光』"<407311996@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yesmeck/waque] waque init Error: Request failed with status code 401 (#10)





 
@andyxm 收到，日志里暴露 token，我先删掉了

**Comment by yesmeck** [comment]
看不出什么问题来，重新 `waque login` 下呢。

**Comment by andyxm** [comment]
试过了，还是这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei Zhu"<notifications@github.com&gt;; 
发送时间: 2020年5月2日(星期六) 晚上11:53
收件人: "yesmeck/waque"<waque@noreply.github.com&gt;; 
抄送: "『燭火夜光』"<407311996@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yesmeck/waque] waque init Error: Request failed with status code 401 (#10)





 
看不出什么问题来，重新 waque login 下呢。

**Comment by shaowin16** [comment]
```
$ DEBUG=axios waque upload

     agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v2/repos/lgoder/vo6cr0/docs',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'lgoder.yuque.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      status: 401,
      message: 'Unauthorized, current organization is not allow access by oauth'
    }
  }
} +789ms
    Error: Request failed with status code 401
```

是不是新版语雀更新API，做了限制了

**Comment by shaowin16** [comment]
```
$ DEBUG=axios waque upload

     agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v2/repos/lgoder/vo6cr0/docs',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'lgoder.yuque.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      status: 401,
      message: 'Unauthorized, current organization is not allow access by oauth'
    }
  }
} +789ms
    Error: Request failed with status code 401
```
是不是语雀更新api，然后不支持了

**Comment by yesmeck** [comment]
'Unauthorized, current organization is not allow access by oauth'


看起来是团队不支持，是不是有什么设置。
