### ISSUE TITLE
新的电脑npm i -g waque后执行waque login后报错

### ISSUE THREAD

**Issue by andyxm** [yesmeck/waque#11]
»   Error: Missing required flag:
»     -t, --token TOKEN
»   See more help with --help

**Comment by yesmeck** [comment]
waque@1.12.1 修正了

**Comment by andyxm** [comment]
ok可以了,晚上在回家看看家里的电脑怎么回事




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei Zhu"<notifications@github.com&gt;; 
发送时间: 2020年4月27日(星期一) 下午5:32
收件人: "yesmeck/waque"<waque@noreply.github.com&gt;; 
抄送: "『燭火夜光』"<407311996@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yesmeck/waque] 新的电脑npm i -g waque后执行waque login后报错 (#11)





 
waque@1.12.1 修正了
