### ISSUE TITLE
导出的文件是md，但是内容却是html

### ISSUE THREAD

**Issue by roy-lau** [yesmeck/waque#12]
![image](https://user-images.githubusercontent.com/22829291/80475491-898e2b80-897b-11ea-8046-45eeb26b6a36.png)

知识库地址 https://www.yuque.com/roylau/blog/learn-nodejs_pm2

**Comment by yesmeck** [comment]
是已知问题，语雀给的就是 HTML，目前不会自动转换到 markdown。

**Comment by yesmeck** [comment]
https://github.com/showdownjs/showdown

**Comment by yesmeck** [comment]
https://github.com/domchristie/turndown

**Comment by yesmeck** [comment]
有空可以加一下，也欢迎 PR
