### ISSUE TITLE
本地上传时文件名不对

### ISSUE THREAD

**Issue by HelperInCa** [yesmeck/waque#15]
待上传文件截图：
![image](https://user-images.githubusercontent.com/32398902/84227576-a1d48880-aa99-11ea-93ef-e852d3576259.png)
原名 `config.md` ，`$ waque upload`上传到语雀后显示的是`实用工具`
`$ waque upload config.md` 还是一样的结果

**Comment by yesmeck** [comment]
没错，h1 会作为标题。

**Comment by HelperInCa** [comment]
可以指定文件名吗

**Comment by HelperInCa** [comment]
> 没错，h1 会作为标题。

可以指定文件名吗

**Comment by yesmeck** [comment]
不能。
