### ISSUE TITLE
代码框编码问题

### ISSUE THREAD

**Issue by Karobben** [yesmeck/waque#19]
错误编码的链接: [Karobben](https://www.yuque.com/liuwenkan/linux/sed2)
本地文件写的
`sed 's/t/T/' file`
上传后, 文档却变成了
`sed &#39;s/t/T/&#39; file`
我idea 用的 atom. 请问, 这是语雀渲染md的问题, 还是瓦雀的问题呀... 搜了一下语雀, 好像, 就我一个人有这问题... 太奇怪了
在gitpage 是没任何问题的. 因为不看语雀, 所以今天才发现-  -

**Comment by yesmeck** [comment]
试了下没发现你说的问题

https://github.com/yesmeck/waque/blob/master/docs/test.md
https://www.yuque.com/waquehq/docs/test

**Comment by Karobben** [comment]
行吧， 谢谢了。 我也不知道问题出在了哪里。 我自己写python脚本调API更新了。 感谢
