### ISSUE TITLE
Missing required flag

### ISSUE THREAD

**Issue by ffywhxf** [yesmeck/waque#2]
F:\111>waque init
 »   Error: Missing required flag:
 »     -t, --token TOKEN
 »   See more help with --help

咋整？

**Comment by yesmeck** [comment]
我没在 Windows 上试过，估计有兼容问题。

**Comment by yesmeck** [comment]
请先确认设置了 token https://github.com/yesmeck/waque#%E7%99%BB%E5%BD%95%E8%AF%AD%E9%9B%80
