### ISSUE TITLE
怎么在 summary.md 中指定目录层次 ？

### ISSUE THREAD

**Issue by coanor** [yesmeck/waque#22]
现在只能单层目录层次，怎么实现多层？

**Comment by coanor** [comment]
我好像找到方式了，语雀文档也有对应说明：

```
- [top-level-1](xxx)
- [top-level-2]() # 这里小括号中不要填，它只是个 place holder
    - [2nd-level-1](zzz) # 注意这里的缩进，类似 yaml 的语法
```

**Comment by maohui66661** [comment]
请问这个方式生效了吗？我按照这个方式配置了，目录虽然生成了，但是相应的文档并没有放入对应的目录中。
summary.md

- [API]()
    - Thresh(thresh)
    - AppRegistry(appRegistry)
    - DevTool(devTool)
    - MediaInfo(mediaInfo)
- [组件]()
    - 组件概要(index)
    - Container(container)
    - Page(page)

waque 版本 ： 1.13.1
