### ISSUE TITLE
如何能让git跳转和语雀跳转一致

### ISSUE THREAD

**Issue by einsitang** [yesmeck/waque#4]
很感谢作者制作了这个软件方便发布到语雀，刚好解决了我们项目内的文档管理这个痛点。
但是这里有一个问题，就是在编写的过程中，我们相对的地址都是根据markdown文件的位置来指定，此时上传到git上（gitlab or github）都可以跳转浏览，但是导入到语雀就不可以了。相反，如果编写时考虑语雀的目录地址，git上阅读就无法访问了，请问有什么办法可以做到兼容呢？

**Comment by yesmeck** [comment]
试试把文档的 url 设置成 `hello-world.md` 这样带上扩展名。

https://www.yuque.com/waquehq/docs/extend#62f79c83

```markdown
---
url: hello-world.md
public: 1
---

# Hello world
```

然后链接 `[Hello](hello-world.md)`

**Comment by einsitang** [comment]
问题解决了，感谢感谢
