### ISSUE TITLE
导出命令的问题！

### ISSUE THREAD

**Issue by dute7liang** [yesmeck/waque#5]
用了一下导出命令。我设置的空节点的目录，咋全部变成空文档，路径变成了#号了。

**Comment by yesmeck** [comment]
知识库可以发我看看么

**Comment by dute7liang** [comment]
o(╥﹏╥)o 今天中午回公司又详细测试了很多次。重现不出来了。[https://www.yuque.com/duteliang/java](https://www.yuque.com/duteliang/java)。
