### ISSUE TITLE
瓦雀的token如何配置在项目中

### ISSUE THREAD

**Issue by cjywoo** [yesmeck/waque#6]
使用waque命令时，每次都提示需要-t 加上token，查阅了语雀的手册，有一步骤提示是配置语雀token的环境变量YUQUE_TOKEN，这一步要如何操作？

**Comment by yesmeck** [comment]
可以试下 https://www.npmjs.com/package/dotenv-cli

**Comment by cjywoo** [comment]
> 可以试下 https://www.npmjs.com/package/dotenv-cli

好的，非常感谢
